function PermissionsSetData(Role: string, EnterEditQuote: boolean, EnterEditOrder: boolean, SetSalesPlan: boolean, ManageSG: boolean, ReadOnlyQuote: boolean, ReadOnlyOrder: boolean, ManageTweaker: boolean, ManageECommerce: boolean, SetControlsPermissions: boolean, AssignDivisionAccess: boolean, Dashboard: boolean, ManagingDefaultListViews: boolean, ManagingIntegrationMappingMills: boolean, SendDcxInfo: boolean, PriceExperimentation: boolean) {
  return { Role, EnterEditQuote, EnterEditOrder, SetSalesPlan, ManageSG, ReadOnlyQuote, ReadOnlyOrder, ManageTweaker, ManageECommerce, SetControlsPermissions, AssignDivisionAccess, Dashboard, ManagingDefaultListViews, ManagingIntegrationMappingMills, SendDcxInfo, PriceExperimentation, key: Math.random() };
}
export const PermissionsData = [
  PermissionsSetData("Admin",true,true,true,true,true,true,true,true,true,true,true,true,true,true,true),
  PermissionsSetData("Read-Only",false,false,false,false,true,true,false,false,false,false,false,false,false,false,false),
  PermissionsSetData("Panel Trader",true,true,false,false,false,false,false,false,false,false,true,false,false,false,false),

];

export const permissionSetData=[
  {
    "Permission Sets" : "Admin",
    "Create/Edit Quote" : true,
    "Create/Edit Order": true,
    "Set Sales Plan": true,
    "Manage Sales Grids": true,
    "Read-Only Quote":true,
    "Read-Only Order":true,
    "Manage Tweaker":true,
    "Manage E-Commerce":true,
    "Set/Controls Permissions":true,
    "Assign Division Access":true,
    "Dashboard":true,
    "Managing Default List Views":true,
    "Managing Integration Mapping Mills to Products":true,
    "Send DCX Info":true,
    "Price Experimentation (Lumber Only)":true
  },
  {
    "Permission Sets" : "Read-Only",
    "Read-Only Quote":true,
    "Read-Only Order":true,
  },
  {
    "Permission Sets" : "Panel Trader",
    "Create/Edit Quote" : true,
    "Create/Edit Order": true,
    "Set Sales Plan": true,
    "Manage Sales Grids": true,
    "Read-Only Quote":true,
    "Read-Only Order":true,
    "Manage E-Commerce":true,
    "Set/Controls Permissions":true,
    "Dashboard":true,
    "Managing Integration Mapping Mills to Products":true,
    "Send DCX Info":true,
    "Price Experimentation (Lumber Only)":true
  },
  {
    "Permission Sets" : "Senior P Trader",
    "Create/Edit Quote" : true,
    "Create/Edit Order": true,
    "Set Sales Plan": true,
    "Manage Sales Grids": true,
    "Read-Only Quote":true,
    "Read-Only Order":true,
    "Manage E-Commerce":true,
    "Set/Controls Permissions":true,
    "Assign Division Access":true,
    "Dashboard":true,
    "Managing Integration Mapping Mills to Products":true,
    "Send DCX Info":true,
  },
  {
    "Permission Sets" : "Lumber Trader",
    "Create/Edit Quote" : true,
    "Create/Edit Order": true,
    "Set Sales Plan": true,
    "Read-Only Quote":true,
    "Read-Only Order":true,
    "Manage Tweaker":true,
    "Set/Controls Permissions":true,
    "Dashboard":true,
    "Managing Integration Mapping Mills to Products":true,
    "Send DCX Info":true,
    "Price Experimentation (Lumber Only)":true
  },
  {
    "Permission Sets" : "Senior L Trader",
    "Create/Edit Quote" : true,
    "Set Sales Plan": true,
    "Manage Sales Grids": true,
    "Read-Only Quote":true,
    "Read-Only Order":true,
    "Manage Tweaker":true,
    "Set/Controls Permissions":true,
    "Dashboard":true,
    "Managing Default List Views":true,
    "Managing Integration Mapping Mills to Products":true,
    "Send DCX Info":true,
    "Price Experimentation (Lumber Only)":true
  },
  {
    "Permission Sets" : "Sales Manager/ Sales Director",
    "Create/Edit Quote" : true,
    "Create/Edit Order": true,
    "Set Sales Plan": true,
    "Read-Only Quote":true,
    "Read-Only Order":true,
    "Manage Tweaker":true,
    "Manage E-Commerce":true,
    "Set/Controls Permissions":true,
    "Assign Division Access":true,
    "Dashboard":true,
  },
  {
    "Permission Sets" : "IBP",
    "Create/Edit Quote" : true,
    "Create/Edit Order": true,
    "Set Sales Plan": true,
    "Manage Sales Grids": true,
    "Read-Only Quote":true,
    "Read-Only Order":true,
    "Manage Tweaker":true,
    "Assign Division Access":true,
    "Dashboard":true,
    "Managing Default List Views":true,
    "Price Experimentation (Lumber Only)":true
  },
  {
    "Permission Sets" : "CX Team", 
    "Manage Sales Grids": true,
    "Read-Only Quote":true,
    "Read-Only Order":true,
    "Manage Tweaker":true,
    "Manage E-Commerce":true,
    "Set/Controls Permissions":true,
    "Assign Division Access":true,
    "Send DCX Info":true,
    "Price Experimentation (Lumber Only)":true
  },
  {
    "Permission Sets" : "National Accts",
    "Create/Edit Quote" : true,
    "Manage Sales Grids": true,
    "Read-Only Quote":true,
    "Read-Only Order":true,
    "Manage Tweaker":true,
    "Manage E-Commerce":true,
    "Set/Controls Permissions":true,
  },
  {
    "Permission Sets" : "Revenue/Analytics",
    "Set Sales Plan": true,
    "Manage Sales Grids": true,
    "Read-Only Quote":true,
    "Read-Only Order":true,
    "Manage Tweaker":true,
    "Assign Division Access":true,
    "Dashboard":true,
    "Managing Default List Views":true,
    "Managing Integration Mapping Mills to Products":true,
    "Send DCX Info":true,
    "Price Experimentation (Lumber Only)":true
  },
  {
    "Permission Sets" : "VP",
    "Create/Edit Quote" : true,
    "Create/Edit Order": true,
    "Set Sales Plan": true,
    "Manage Sales Grids": true,
    "Read-Only Quote":true,
    "Read-Only Order":true,
    "Manage Tweaker":true,
    "Manage E-Commerce":true,
    "Set/Controls Permissions":true,
    "Assign Division Access":true,
    "Dashboard":true,
    "Send DCX Info":true,
    "Price Experimentation (Lumber Only)":true
  },
  {
    "Permission Sets" : "QA Team",
    "Create/Edit Quote" : true,
    "Create/Edit Order": true,
    "Set Sales Plan": true,
    "Manage Sales Grids": true,
    "Read-Only Quote":true,
    "Read-Only Order":true,
    "Manage Tweaker":true,
    "Manage E-Commerce":true,
    "Dashboard":true,
    "Managing Default List Views":true,
    "Managing Integration Mapping Mills to Products":true,
    "Send DCX Info":true,
    "Price Experimentation (Lumber Only)":true
  },
  {
    "Permission Sets" : "Developer",
    "Create/Edit Quote" : true,
    "Create/Edit Order": true,
    "Set Sales Plan": true,
    "Manage Sales Grids": true,
    "Read-Only Quote":true,
    "Read-Only Order":true,
    "Manage Tweaker":true,
    "Send DCX Info":true,
    "Price Experimentation (Lumber Only)":true
  },
  {
    "Permission Sets" : "Transportation Team",
    "Create/Edit Quote" : true,
    "Manage Sales Grids": true,
    "Read-Only Quote":true,
    "Read-Only Order":true,
    "Manage Tweaker":true,
    "Manage E-Commerce":true,
    "Set/Controls Permissions":true,
    "Assign Division Access":true,
    "Dashboard":true,
    "Managing Default List Views":true,
    "Managing Integration Mapping Mills to Products":true,
  }
]