export const UsersData = [
	{
		id: 1,
		first_name: 'Emiline',
		last_name: 'McClune',
		email: 'emcclune0@gp.com',
		role: 'Business Analyst',
		temporaryPermission: 'C',
		temporaryPermissionDate: '09/02/2023',
	},
	{
		id: 2,
		first_name: 'Freddy',
		last_name: 'Ingleston',
		email: 'fingleston1@gp.com',
		role: 'Technical Dev',
		temporaryPermission: 'C',
		temporaryPermissionDate: '09/02/2023',
	},
	{
		id: 3,
		first_name: 'Travis',
		last_name: 'Bergstram',
		email: 'tbergstram2@gp.com',
		role: 'Specialist',
		temporaryPermission: 'C',
		temporaryPermissionDate: '09/02/2023',
	},
	{
		id: 4,
		first_name: 'Hannah',
		last_name: 'Knighton',
		email: 'hknighton3@gp.com',
		role: 'Consultant',
		temporaryPermission: 'C',
		temporaryPermissionDate: '09/02/2023',
	},
	{
		id: 5,
		first_name: 'Sally',
		last_name: 'Naulty',
		email: 'snaulty4@gp.com',
		role: 'Associate',
		temporaryPermission: 'C',
		temporaryPermissionDate: '09/02/2023',
	},
	{
		id: 6,
		first_name: 'Ananya',
		last_name: 'Dhar',
		email: 'ananya@gp.com',
		role: 'Analyst',
		temporaryPermission: 'C',
		temporaryPermissionDate: '09/02/2023',
	},
	{
		id: 7,
		first_name: 'Raju',
		last_name: 'Kumar',
		email: 'rkumar@gp.com',
		role: 'Associate',
		temporaryPermission: 'C',
		temporaryPermissionDate: '09/02/2023',
	},
	{
		id: 8,
		first_name: 'Raju',
		last_name: 'Kumar',
		email: 'rkumar@gp.com',
		role: 'Associate',
		temporaryPermission: 'C',
		temporaryPermissionDate: '09/02/2023',
	},
	{
		id: 9,
		first_name: 'Raju',
		last_name: 'Kumar',
		email: 'rkumar@gp.com',
		role: 'Associate',
		temporaryPermission: 'C',
		temporaryPermissionDate: '09/02/2023',
	},
];

export const permissionSets = [
	{
		id: 1,
		permission: 'Admin',
		subdivision: 'SP',
	},
	{
		id: 2,
		permission: 'Leader',
		subdivision: 'SP',
	},
	{
		id: 3,
		permission: 'Sales Manager',
		subdivision: 'SP',
	},
	{
		id: 4,
		permission: 'Advisor',
		subdivision: 'SL',
	},
	{
		id: 5,
		permission: 'Trader',
		subdivision: 'SL',
	},
	{
		id: 6,
		permission: 'Senior Trader',
		subdivision: 'SL',
	},
];
