// data
// Component Utility : This is the data page which has all the data in Json format which is used by all the components
// Author Gautam Malhotra on 1-3-2023
// -------------------------
//This is the data which is used by different components, it is hard coded now but will be replaced by API calls once the
//backend architecture is confirmed.
import { GridColDef } from '@mui/x-data-grid';
import CheckIcon from '@mui/icons-material/Check';
import { GridRowsProp } from '@mui/x-data-grid';

//The actual implementation will have call to a API.
export function OrdersGridcreateData(
	id: number,
	division: string,
	subDivision: string,
	firstName: string,
	lastName: string,
	email: string,
	permissionSet: string,
	activeUser: boolean,
	temporaryPermission: string,
	temporaryPermissionStartDate: string,
	temporaryPermissionEndDate: string,
) {
	return {
		id,
		division,
		subDivision,
		firstName,
		lastName,
		email,
		permissionSet,
		activeUser,
		temporaryPermission,
		temporaryPermissionStartDate,
		temporaryPermissionEndDate,
		key: Math.random(),
	};
}
//The actual implementation will have call to a API.
export const OrdersGridrows: GridRowsProp = [
	OrdersGridcreateData(
		1,
		'SL',
		'',
		'Talladega',
		'MPU',
		'raj@gapac.com',
		'',
		false,
		'',
		'',
		'',
	),
	OrdersGridcreateData(
		2,
		'SL',
		'',
		'Piedmont-R',
		'NOA',
		'john@gapac.com',
		'',
		false,
		'',
		'',
		'',
	),
	OrdersGridcreateData(
		3,
		'SL',
		'',
		'Piedmont-R',
		'NOA',
		'rama@gapac.com',
		'',
		false,
		'',
		'',
		'',
	),

	OrdersGridcreateData(
		4,
		'SP',
		'PLY',
		'Piedmont-R',
		'NOA',
		'Kri6@gapac.com',
		'Sales Manager',
		true,
		'Trader',
		'02/14/2023',
		'02/14/2023',
	),
	OrdersGridcreateData(
		5,
		'SL',
		'',
		'Talladega',
		'MPU',
		'Kri5@gapac.com',
		'',
		false,
		'',
		'',
		'',
	),
	OrdersGridcreateData(
		6,
		'SL',
		'',
		'David',
		'Ugam',
		'gautam@gapac.com',
		'Manager',
		true,
		'Trader',
		'02/14/2023',
		'02/14/2023',
	),
	OrdersGridcreateData(
		7,
		'SP',
		'OSB',
		'Talladega',
		'NOA',
		'rohan@gapac.com',
		'',
		false,
		'',
		'',
		'',
	),
	OrdersGridcreateData(
		8,
		'SP',
		'PLY',
		'Piedmont-R',
		'MPU',
		'raja@gapac.com',
		'Advisor',
		true,
		'Manager',
		'02/14/2023',
		'02/14/2023',
	),
	OrdersGridcreateData(
		9,
		'SL',
		'',
		'Talladega',
		'MPU',
		'madan@gapac.com',
		'',
		false,
		'',
		'',
		'',
	),
	OrdersGridcreateData(
		10,
		'SL',
		'',
		'Piedmont-R',
		'NOA',
		'Kri3@gapac.com',
		'Manager',
		true,
		'Sales',
		'02/14/2023',
		'02/14/2023',
	),
	OrdersGridcreateData(
		11,
		'SP',
		'OSB',
		'Talladega',
		'MPU',
		'dilip@gapac.com',
		'',
		false,
		'',
		'',
		'',
	),
	OrdersGridcreateData(
		12,
		'SL',
		'',
		'Piedmont-R',
		'MPU',
		'Kris@gapac.com',
		'Trader',
		true,
		'Admin',
		'02/14/2023',
		'02/14/2023',
	),
];
